### ISSUE TITLE
Missing service to add role to a Group

### ISSUE THREAD

**Issue by dmartinol** [zemirco/keycloak#3]
GroupsService is missing the API to manage the roles mapped to a given group.
At least these two methods should be added:
func (s *GroupsService) AddRealmRoles(ctx context.Context, realm, group *Group, roles []*Role) (*http.Response, error)
func (s *GroupsService) RemoveRealmRoles(ctx context.Context, realm, group *Group, roles []*Role) (*http.Response, error)

**Comment by zemirco** [comment]
This was added in https://github.com/zemirco/keycloak/pull/4.
